import Vue from "vue";

// Comment on components you do not use in project.
import OurAccordion from "@ilevel/our.ui.accordion";
import OurAvatar from "@ilevel/our.ui.avatar";
import OurButton from "@ilevel/our.ui.button";
import OurDropdown from "@ilevel/our.ui.button-dropdown";
import OurButtonGroup from "@ilevel/our.ui.button-group";
import OurLink from "@ilevel/our.ui.button-link";
import OurExpandButton from "@ilevel/our.ui.button-expand";
import OurExpandButtonItem from "@ilevel/our.ui.button-expand-item";
import OurCard from "@ilevel/our.ui.container-card";
import OurConfirmModal from "@ilevel/our.ui.container-modal-confirm";
import OurPageModal from "@ilevel/our.ui.container-modal-page";
import OurPage from "@ilevel/our.ui.container-page";
import OurRow from "@ilevel/our.ui.container-row";
import OurSvgIcon from "@ilevel/our.ui.icon-svg";
import OurInput from "@ilevel/our.ui.input";
import OurCheckbox from "@ilevel/our.ui.input-checkbox";
import OurCheckboxGroup from "@ilevel/our.ui.input-checkbox-group";
import OurMultiStateCheckbox from "@ilevel/our.ui.input-checkbox-multi-state";
import OurDatePicker from "@ilevel/our.ui.input-date-picker";
import OurDateRangePicker from "@ilevel/our.ui.input-date-picker-range";
import OurFileInput from "@ilevel/our.ui.input-file";
import OurMoneyInput from "@ilevel/our.ui.input-money";
import OurPhoneInput from "@ilevel/our.ui.input-phone";
import OurRadioCard from "@ilevel/our.ui.input-radio-card";
import OurRadioGroup from "@ilevel/our.ui.input-radio-group";
import OurRatingInput from "@ilevel/our.ui.input-rating";
import OurSelect from "@ilevel/our.ui.input-select";
import OurMultiselect from "@ilevel/our.ui.input-select-multi";
import OurSwitch from "@ilevel/our.ui.input-switch";
import OurTextarea from "@ilevel/our.ui.input-textarea";
import OurTableList from "@ilevel/our.ui.table-list";
import OurTable from "@ilevel/our.ui.table";
import OurLanguages from "@ilevel/our.ui.languages";
import OurLoader from "@ilevel/our.ui.loader";
import OurTopLoader from "@ilevel/our.ui.loader-top";
import OurLogo from "@ilevel/our.ui.logo";
import OurPagination from "@ilevel/our.ui.pagination";
import OurStepper from "@ilevel/our.ui.stepper";
import OurTextBlock from "@ilevel/our.ui.text-block";
import OurHint from "@ilevel/our.ui.text-hint";
import OurMoney from "@ilevel/our.ui.text-money";
import OurNotify from "@ilevel/our.ui.text-notify";
import OurTag from "@ilevel/our.ui.text-tag";

Vue.component("OurAccordion", OurAccordion);
Vue.component("OurAvatar", OurAvatar);
Vue.component("OurButton", OurButton);
Vue.component("OurDropdown", OurDropdown);
Vue.component("OurButtonGroup", OurButtonGroup);
Vue.component("OurLink", OurLink);
Vue.component("OurExpandButton", OurExpandButton);
Vue.component("OurExpandButtonItem", OurExpandButtonItem);
Vue.component("OurCard", OurCard);
Vue.component("OurConfirmModal", OurConfirmModal);
Vue.component("OurPageModal", OurPageModal);
Vue.component("OurPage", OurPage);
Vue.component("OurRow", OurRow);
Vue.component("OurSvgIcon", OurSvgIcon);
Vue.component("OurInput", OurInput);
Vue.component("OurCheckbox", OurCheckbox);
Vue.component("OurCheckboxGroup", OurCheckboxGroup);
Vue.component("OurMultiStateCheckbox", OurMultiStateCheckbox);
Vue.component("OurDatePicker", OurDatePicker);
Vue.component("OurDateRangePicker", OurDateRangePicker);
Vue.component("OurFileInput", OurFileInput);
Vue.component("OurMoneyInput", OurMoneyInput);
Vue.component("OurPhoneInput", OurPhoneInput);
Vue.component("OurRadioCard", OurRadioCard);
Vue.component("OurRadioGroup", OurRadioGroup);
Vue.component("OurRatingInput", OurRatingInput);
Vue.component("OurSelect", OurSelect);
Vue.component("OurMultiselect", OurMultiselect);
Vue.component("OurSwitch", OurSwitch);
Vue.component("OurTextarea", OurTextarea);
Vue.component("OurTableList", OurTableList);
Vue.component("OurTable", OurTable);
Vue.component("OurLanguages", OurLanguages);
Vue.component("OurLoader", OurLoader);
Vue.component("OurTopLoader", OurTopLoader);
Vue.component("OurLogo", OurLogo);
Vue.component("OurPagination", OurPagination);
Vue.component("OurStepper", OurStepper);
Vue.component("OurTextBlock", OurTextBlock);
Vue.component("OurHint", OurHint);
Vue.component("OurMoney", OurMoney);
Vue.component("OurNotify", OurNotify);
Vue.component("OurTag", OurTag);
